#!/bin/sh
 PROG=./differ

 case $1 in
 1) T=differByOneTests/true* ;;
 2) T=differByOneTests/false* ;;
 esac

 if [ A$T != A ]
 then
    for i in $T
    do
    echo =================  $i  ==================
    $PROG < $i
    done
 else
    echo Usage $0 "[1|2]"
 fi